### ISSUE TITLE
Return of function json.dumps

### ISSUE THREAD

**Issue by RSiopa** [miguelriemoliveira/psr_21-22#11]
Good afternoon,
When printing the inputs like asked in the TP1 with the json.dumps method, they take a lot more space than the originally intended pprint method. Is this normal because json does things differently and we should leave it like this or do you think this is some problem on our part?
![Screenshot at 2021-10-30 15-55-22](https://user-images.githubusercontent.com/92531714/139538274-15477389-8975-493a-93f3-250dad8b9431.png)

**Comment by miguelriemoliveira** [comment]
Hi @RSiopa ,

you mean more horizontal space? If so take a look at the indent argument for the function json.dumps

**Comment by PedroCarvalho98** [comment]
Good morning professor @miguelriemoliveira, 
What we meant was that when printing the list of namedtuples 'inputs', the json.dumps() is doing '\n' between every attribute of the namedtuple instead of just doing '\n' between the elements of the list 'inputs'. So we wanted to ask you if is this normal because json does things differently and we should leave it like this or do you think this is some problem on our part?

**Comment by miguelriemoliveira** [comment]
Please copy paste the text an not an image. The image is very hard to see.

https://stackoverflow.com/questions/14901245/how-to-style-a-json-block-in-github-wiki
